// front-end/yacht-tourism-front-end/src/app/add-yacht/add-yacht.component.ts
import { Component } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-add-yacht',
  standalone: true,
  imports: [],
  templateUrl: './add-yacht.component.html',
  styleUrl: './add-yacht.component.css'
})
export class AddYachtComponent {
  shipid: number = 3;
  location: string = '';
  LogBook: string = '';
  owner: string = '';
  IPFS: string = '';
  yachtName: string = '';
  model: string = '';
  capacity: string = '';
  description: string = '';
  skipper: string = '';
  length: string = '';
  width: string = '';
  bedrooms: string = '';
  amenities: string = '';
  crewDetails: string = '';
  safetyFeatures: string = '';

  constructor(private http: HttpClient) { 
    this.shipid++;
  }

  addYacht(): void {
    const yachtData = {
      ShipId: this.shipid,
      Location: this.location,
      LogBook: 'logs',
      Owner: this.owner,
      IPFS: 'photo.png',
      Name: this.yachtName,
      Model: this.model,
      Capacity: this.capacity,
      Description: this.description,
      Length: this.length,
      Width: this.width,
      Amenities: this.amenities,
      CrewDetails: this.crewDetails,
      SafetyFeatures: this.safetyFeatures
    };

    this.http.post<any>('http://localhost:8080/add_yacht', yachtData)
      .subscribe(
        response => {
          console.log('Yacht added successfully:', response);
          // Handle success response
        },
        error => {
          console.error('Error adding yacht:', error);
          // Handle error response
        }
      );
  }
}

<!-- Navigation bar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" routerLink="/">Yacht Rentals</a>
    <ul class="navbar-nav">
        <li class="nav-item"><button type="button" class="btn btn-outline-primary btn-lg"><a href="/add-yacht" style="text-decoration: none;">Add Yacht</a></button></li>
        <li class="nav-item"><button type="button" class="btn btn-outline-primary btn-lg"><a href="/book-yacht" style="text-decoration: none;">Book Yacht</a></button></li>
        <li class="nav-item"><button type="button" class="btn btn-outline-primary btn-lg"><a href="/list-yacht" style="text-decoration: none;">Yacht List</a></button></li>
    </ul>
</nav>

<!-- Yacht owner form -->
<div class="container mt-4">
    <h2>Add Yacht</h2>
    <form>
        <!-- Yacht Name -->
        <div class="form-group">
            <label for="yachtName">Yacht Name:</label>
            <input type="text" class="form-control" id="yachtName" placeholder="Enter yacht name">
        </div>

        <!-- Description -->
        <div class="form-group">
            <label for="description">Description:</label>
            <textarea class="form-control" id="description" rows="3" placeholder="Describe the yacht"></textarea>
        </div>

        <!-- Location -->
        <div class="form-group col-md-6">
            <label for="location">Location:</label>
            <input type="text" class="form-control" id="location" placeholder="Provide the yacht location">
        </div>

        <!-- Owner -->
        <div class="form-group col-md-6">
            <label for="owner">Owner:</label>
            <input type="text" class="form-control" id="owner" placeholder="Specify yacht owner">
        </div>

        <!-- Skipper -->
        <div class="form-group col-md-6">
            <label for="skipper">Skipper:</label>
            <input type="text" class="form-control" id="skipper" placeholder="Provide skipper information">
        </div>

        <!-- Capacity -->
        <div class="form-group col-md-6">
            <label for="capacity">Capacity:</label>
            <input type="text" class="form-control" id="capacity" placeholder="Enter maximum capacity">
        </div>

        <!-- Length and Width -->
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="length">Length (LOA):</label>
                <input type="text" class="form-control" id="length" placeholder="Enter yacht length (feet/meters)">
            </div>
            <div class="form-group col-md-6">
                <label for="width">Width (Beam):</label>
                <input type="text" class="form-control" id="width" placeholder="Enter yacht width (feet/meters)">
            </div>
        </div>

        <!-- Model and Bedrooms -->
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="model">Model:</label>
                <input type="text" class="form-control" id="model" placeholder="Enter yacht model">
            </div>
            <div class="form-group col-md-6">
                <label for="bedrooms">Number of Bedrooms:</label>
                <input type="text" class="form-control" id="bedrooms" placeholder="Enter number of bedrooms">
            </div>
        </div>

        <!-- Amenities -->
        <div class="form-group">
            <label for="amenities">Amenities:</label>
            <textarea class="form-control" id="amenities" rows="3" placeholder="List yacht amenities"></textarea>
        </div>

        <!-- Crew Details -->
        <div class="form-group">
            <label for="crew">Crew Details:</label>
            <textarea class="form-control" id="crew" rows="3" placeholder="Describe the crew members"></textarea>
        </div>

        <!-- Safety Features -->
        <div class="form-group">
            <label for="safetyFeatures">Safety Features:</label>
            <textarea class="form-control" id="safetyFeatures" rows="3" placeholder="Highlight safety equipment"></textarea>
        </div>

        <!-- Photos (upload input) -->
        <div class="form-group">
            <label for="photos">Photos:</label>
            <input type="file" class="form-control-file" id="photos" accept="image/*" multiple>
        </div>

        <!-- Submit button -->
        <button type="submit" class="btn btn-primary">Add Yacht</button>
    </form>
</div>

// front-end-react-app/src/components/addYacht.js
import React from 'react';
import axios from 'axios';
import { Container, Form, Button, Col, Row } from 'react-bootstrap';

class AddYacht extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      yachtId: '',
      yachtName: '',
      description: '',
      location: '',
      owner: '',
      skipper: '',
      capacity: '',
      length: '',
      width: '',
      model: '',
      bedrooms: '',
      amenities: '',
      crew: '',
      safetyFeatures: '',
      photos: '',
    };
  }

  /*uploadToIpfs = async () => {
    const uploadUrl = await upload({
      data: [photos],
      options: {
        uploadWithGatewayUrl: true,
        uploadWithoutDirectory: true
      }
    });
https://fuchsia-absent-goose-826.mypinata.cloud/ipfs/
    console.log('Upload URL: ', uploadUrl)
  };
*/
  handleChange = (event) => {
    const { name, value } = event.target;
    this.setState({ [name]: value });
  };

  handleFileChange = (event) => {
    this.setState({ photos: `yachtPicture.jpg` });
  };

  handleSubmit = async (event) => {
    event.preventDefault();
    const {
      yachtId,
      yachtName,
      description,
      location,
      owner,
      skipper,
      capacity,
      length,
      width,
      model,
      bedrooms,
      amenities,
      crew,
      safetyFeatures,
      photos, 
    } = this.state;
  

    // Concatenate form field values with underscore
    const inputValue = `${yachtId}_${location}_logs_${owner}_${photos}_${yachtName}_${model}_${capacity}_${description}_${skipper}_${length}_${width}_${amenities}_${crew}_${safetyFeatures}`;

    console.log('Concatenated input value:', inputValue);

    try {
      await axios.get(`http://localhost:8085/add_Yacht/${inputValue}`);
      console.log('GET request successful');
      // You can do something after the request is successful
    } catch (error) {
      console.error('Error sending GET request:', error);
    }

  };

render() {
    const {
      yachtId,
      yachtName,
      description,
      location,
      owner,
      skipper,
      capacity,
      length,
      width,
      model,
      bedrooms,
      amenities,
      crew,
      safetyFeatures,
      photos
    } = this.state;

    return (
      <div>
        {/* Yacht owner form */}
        <Container className="mt-4">
          <h2>Add Yacht</h2>
          <Form onSubmit={this.handleSubmit}>
            <Form.Group controlId="yachtId">
              <Form.Label>Yacht ID:</Form.Label>
              <Form.Control type="text" name="yachtId" value={yachtId} onChange={this.handleChange} placeholder="Enter yacht ID" />
            </Form.Group>
            <Form.Group controlId="yachtName">
              <Form.Label>Yacht Name:</Form.Label>
              <Form.Control type="text" name="yachtName" value={yachtName} onChange={this.handleChange} placeholder="Enter yacht name" />
            </Form.Group>
            <Form.Group controlId="description">
              <Form.Label>Description:</Form.Label>
              <Form.Control as="textarea" name="description" value={description} onChange={this.handleChange} rows={3} placeholder="Describe the yacht" />
            </Form.Group>
            <Row>
            <Form.Group controlId="location" as={Col}>
              <Form.Label>Location:</Form.Label>
              <Form.Control type="text" name="location" value={location} onChange={this.handleChange} placeholder="Provide the yacht location" />
            </Form.Group>
            <Form.Group controlId="owner" as={Col}>
              <Form.Label>Owner:</Form.Label>
              <Form.Control type="text" name="owner" value={owner} onChange={this.handleChange} placeholder="Specify yacht owner" />
            </Form.Group>
            </Row>
            <Row>
            <Form.Group controlId="skipper" as={Col}>
              <Form.Label>Skipper:</Form.Label>
              <Form.Control type="text" name="skipper" value={skipper} onChange={this.handleChange} placeholder="Provide skipper information" />
            </Form.Group>
            <Form.Group controlId="capacity" as={Col}>
              <Form.Label>Capacity:</Form.Label>
              <Form.Control type="text" name="capacity" value={capacity} onChange={this.handleChange} placeholder="Enter maximum capacity" />
            </Form.Group>
            </Row>
            <Row>
              <Form.Group as={Col} controlId="length">
                <Form.Label>Length (LOA):</Form.Label>
                <Form.Control type="text" name="length" value={length} onChange={this.handleChange} placeholder="Enter yacht length (feet/meters)" />
              </Form.Group>
              <Form.Group as={Col} controlId="width">
                <Form.Label>Width (Beam):</Form.Label>
                <Form.Control type="text" name="width" value={width} onChange={this.handleChange} placeholder="Enter yacht width (feet/meters)" />
              </Form.Group>
            </Row>
            <Row>
              <Form.Group as={Col} controlId="model">
                <Form.Label>Model:</Form.Label>
                <Form.Control type="text" name="model" value={model} onChange={this.handleChange} placeholder="Enter yacht model" />
              </Form.Group>
              <Form.Group as={Col} controlId="bedrooms">
                <Form.Label>Number of Bedrooms:</Form.Label>
                <Form.Control type="text" name="bedrooms" value={bedrooms} onChange={this.handleChange} placeholder="Enter number of bedrooms" />
              </Form.Group>
            </Row>
            <Form.Group controlId="amenities">
              <Form.Label>Amenities:</Form.Label>
              <Form.Control as="textarea" name="amenities" value={amenities} onChange={this.handleChange} rows={3} placeholder="List yacht amenities" />
            </Form.Group>
            <Form.Group controlId="crew">
              <Form.Label>Crew Details:</Form.Label>
              <Form.Control as="textarea" name="crew" value={crew} onChange={this.handleChange} rows={3} placeholder="Describe the crew members" />
            </Form.Group>
            <Form.Group controlId="safetyFeatures">
              <Form.Label>Safety Features:</Form.Label>
              <Form.Control as="textarea" name="safetyFeatures" value={safetyFeatures} onChange={this.handleChange} rows={3} placeholder="Highlight safety equipment" />
            </Form.Group>
            <Form.Group controlId="photos">
              <Form.Label>Add Photos:</Form.Label>
              <Form.Control type="file" name="photos" onChange={this.handleFileChange} accept="image/*" />
            </Form.Group>
            <br></br>
            <Button variant="primary" type="submit">Add Yacht</Button>
          </Form>
          <br></br>
        </Container>
      </div>
    );
  }
}

export default AddYacht;
